### ISSUE TITLE
Error detected while processing function pipenv#activate:

### ISSUE THREAD

**Issue by xarthurx** [PieterjanMontens/vim-pipenv#8]
![image](https://user-images.githubusercontent.com/1921878/56078449-721fe700-5de8-11e9-8229-f31550be1169.png)

Got this when opening a file inside a pipenv.

**Comment by timjstewart** [comment]
looks like shell_error should be v:shell_error in autoload/pipenv.vim.

**Comment by PieterjanMontens** [comment]
Thanks, I'll look into it

**Comment by PieterjanMontens** [comment]
Hmm, weird, shell_error [should work](http://vimdoc.sourceforge.net/htmldoc/eval.html#v:shell_error)... still, v:shell_error is recommended, so I'll be patching it :+1:
